-- MySQL Script generated by MySQL Workbench
-- Sun Apr 18 20:41:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library_dbms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_dbms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_dbms` DEFAULT CHARACTER SET utf8 ;
USE `library_dbms` ;

-- -----------------------------------------------------
-- Table `library_dbms`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_dbms`.`user` (
  `user_id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` MEDIUMTEXT NOT NULL,
  `unpaid_fees` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_dbms`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_dbms`.`author` (
  `ISBN_number` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN_number`, `name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_dbms`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_dbms`.`books` (
  `title` VARCHAR(45) NOT NULL,
  `publication_year` DATE NOT NULL,
  `copy_number` INT NOT NULL,
  `subject` VARCHAR(45) NOT NULL,
  `ISBN_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN_number`),
  CONSTRAINT `ISBN_numberc`
    FOREIGN KEY (`ISBN_number`)
    REFERENCES `library_dbms`.`author` (`ISBN_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_dbms`.`shelf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_dbms`.`shelf` (
  `shelf_id` INT NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`shelf_id`),
  UNIQUE INDEX `shelf_id_UNIQUE` (`shelf_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_dbms`.`order_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_dbms`.`order_books` (
  `user_id` INT NOT NULL,
  `ISBN_number` VARCHAR(45) NOT NULL,
  `status_of_book` VARCHAR(45) NOT NULL,
  `date_booked` DATE NOT NULL,
  `date_due` DATE NULL,
  PRIMARY KEY (`ISBN_number`, `user_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_ide`
    FOREIGN KEY (`user_id`)
    REFERENCES `library_dbms`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ISBN_numberd`
    FOREIGN KEY (`ISBN_number`)
    REFERENCES `library_dbms`.`books` (`ISBN_number`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_dbms`.`books_place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_dbms`.`books_place` (
  `shelf_id` INT NOT NULL,
  `ISBN_number` VARCHAR(45) NOT NULL,
  `book_quantity` INT NOT NULL,
  PRIMARY KEY (`shelf_id`, `ISBN_number`),
  INDEX `ISBN_number_idx` (`ISBN_number` ASC) VISIBLE,
  CONSTRAINT `shelf_ida`
    FOREIGN KEY (`shelf_id`)
    REFERENCES `library_dbms`.`shelf` (`shelf_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ISBN_numbere`
    FOREIGN KEY (`ISBN_number`)
    REFERENCES `library_dbms`.`books` (`ISBN_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_dbms`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_dbms`.`friends` (
  `user_id1` INT NOT NULL,
  `user_id2` INT NOT NULL,
  PRIMARY KEY (`user_id2`, `user_id1`),
  INDEX `user_id1_idx` (`user_id1` ASC) VISIBLE,
  CONSTRAINT `user_id1c`
    FOREIGN KEY (`user_id1`)
    REFERENCES `library_dbms`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_id2d`
    FOREIGN KEY (`user_id2`)
    REFERENCES `library_dbms`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_dbms`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_dbms`.`review` (
  `user_id` INT NOT NULL,
  `ISBN_number` VARCHAR(45) NOT NULL,
  `rating` INT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`user_id`, `ISBN_number`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `ISBN_number_idx` (`ISBN_number` ASC) VISIBLE,
  CONSTRAINT `user_idb`
    FOREIGN KEY (`user_id`)
    REFERENCES `library_dbms`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ISBN_numberb`
    FOREIGN KEY (`ISBN_number`)
    REFERENCES `library_dbms`.`author` (`ISBN_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_dbms`.`add_to_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_dbms`.`add_to_cart` (
  `user_id` INT NOT NULL,
  `ISBN_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`, `ISBN_number`),
  INDEX `ISBN_number_idx` (`ISBN_number` ASC) VISIBLE,
  CONSTRAINT `user_ida`
    FOREIGN KEY (`user_id`)
    REFERENCES `library_dbms`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ISBN_numbera`
    FOREIGN KEY (`ISBN_number`)
    REFERENCES `library_dbms`.`books` (`ISBN_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
